### ISSUE TITLE
Make all pages accessible through recipe url

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/cookingassistant#19]
Currently all recipes are added to the app when navigating to "recipes" if you go directly to a recipe URL, the recipes won't be loaded and therefore, no recipe will be shown.

### TODO
* [x] Prepare recipes in `App.vue`
  * [x] Remove recipe logic from `Recipes.vue`
* [x] Load recipe based on `$route.params.name` (same as recipe)
*
