### ISSUE TITLE
Module to add recipe/send suggested recipe

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/cookingassistant#2]
### Criteria 
* Create recipe in structure that is compatible with existing recipes

### Todo
* Create new page with 
  * [x] Title
  * [x] Short description (teaser)
  * [x] List of ingredients (amount, unit, text) (as programmatically "addable" steps(components)
  * [x] steps (as programmatically "addable" steps (components))
  * [x] categories
  * [x] number of portions/servings
  * [x] style page
  * [ ] Make it possible to rearrange list components (ingredients and steps) _use [transitions](https://www.w3schools.com/css/css3_transitions.asp)_
  * [x] Enable user to send recipe to `henriette.steenhoff@gmail.com`

**Comment by frksteenhoff** [comment]
Started integrating changes in 93aa0822f4f21e0e369114151261a2a4c34080a5
