### ISSUE TITLE
Extend functionality and content on recipe page

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/cookingassistant#4]
### TODO
* [x] Add information about number of portions
* [x] Pro tips with extra information about how to make the dish
* [x] Make internal links between recipes to suggest combinations

**Comment by frksteenhoff** [comment]
Added protip with 64a2885 and a9aaa71
